name: cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    name: cleanup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Declare PR Status Variables
        run: echo "is_merged_pr=true" >> $GITHUB_ENV
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true

      - name: Clean up Sandbox
        run: 'echo cleanup sandbox environment'
        if: ${{ env.is_merged_pr }} == "true" && startsWith(${{ github.head_ref }}, "sandbox-")
