name: main

on:
  push

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: v2-${{ hashFiles('yarn.lock') }}
        if: |
          ${{ ( startsWith(env.GITHUB_REF_SLUG, 'sandbox-') && contains(github.event.head_commit.message, '#test')) ||
          ! startsWith(env.GITHUB_REF_SLUG, 'sandbox-') }}
      - name: Run unit tests for sandbox branches
        run: echo run unit test for sandbox branch when keyword is matched
        if: startsWith(env.GITHUB_REF_SLUG, 'sandbox-') && contains(github.event.head_commit.message, '#test')

      - name: Run unit tests for other branches
        run: ./ci/test.sh
        if: ${{ ! startsWith(env.GITHUB_REF_SLUG, 'sandbox-') }}

      - name: Build Release
        run: npm run build

      - name: Fail the workflow if test is skipped
        run: 'exit 1'
        if: startsWith(env.GITHUB_REF_SLUG, 'sandbox-') && ! contains(github.event.head_commit.message, '#test')
