name: test

on:
  workflow_dispatch:
    inputs:
      run_test:
        description: 'run unit tests'
        required: true
        default: false

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: 'echo run unit test'
        if: github.event.inputs.run_test == 'true'

      - name: 'fail the workflow if unit tests are skipped'
        run: exit 1
        if: github.event.inputs.run_test == 'false'
